[packages]
packages = [
	"git",
	"gcc",
	"nano",
	"archiso"
]

[repos]
# alci_repo = { SigLevel = "Optional TrustedOnly", Server = "https://arch-linux-calamares-installer.github.io/$repo/$arch" }
alci_repo = { SigLevel = "Optional TrustedOnly", Server = "https://repo.0x01.wtf/irislinux/testing/os/x86_64" }
